import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {chromium} from 'playwright';
const dir=new URL('../',import.meta.url);
const fsData=await fs.readFile(new URL('assets/techniques.json',dir),'utf8'),fsCalc=await fs.readFile(new URL('assets/calculator.js',dir),'utf8');
let html=await fs.readFile(new URL('assets/index.html',dir),'utf8');
html=html.replace('/*__TECHNIQUES__*/',()=>fsData).replace('/*__CALCULATOR__*/',()=>fsCalc);
const browser=await chromium.launch({executablePath:process.env.CHROME_BINARY,headless:true,args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:393,height:852}});await context.route('https://shottime.local/**',r=>r.fulfill({contentType:'text/html',body:html}));const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto('https://shottime.local/');
async function setup(){await page.locator('#setup-panel>summary').click();assert.ok(await page.locator('#sheet-dialog').evaluate(n=>n.open));}
async function close(){await page.locator('#close-sheet').click();assert.equal(await page.locator('#sheet-dialog').evaluate(n=>n.open),false);}
await setup();await page.locator('#activity').fill('50');await page.locator('button[form="activity-form"]').click();
assert.equal(await page.locator('#sheet-dialog').evaluate(n=>n.open),false);assert.equal(await page.locator('.shot').count(),73);assert.equal(await page.locator('.time').first().textContent(),'1m 32s');assert.match(await page.locator('#toast').textContent(),/updated/);
await setup();await page.locator('.film-options button[data-film="mx125"]').click();assert.equal(await page.locator('#film-small').inputValue(),'mx125');assert.match(await page.locator('#toast').textContent(),/MX125 saved/);
await page.locator('.film-options button[data-film="t200"]').click();await close();
await page.locator('#pipe-filter summary').click();await page.locator('#pipe-filter').getByRole('button',{name:'Clear',exact:true}).click();await page.locator('#pipe-filter input[value="2"]').check();await page.locator('#pipe-filter input[value="3"]').check();await close();
await page.locator('#schedule-filter summary').click();await page.locator('#schedule-filter').getByRole('button',{name:'Clear',exact:true}).click();await page.locator('#schedule-filter input[value="STD"]').check();await close();assert.equal(await page.locator('.shot').count(),2);
await page.reload();assert.equal(await page.locator('.shot').count(),2);assert.equal(await page.locator('#film-small').inputValue(),'mx125');
await page.locator('#open-print').click();assert.equal(await page.locator('#sheet-title').textContent(),'Print options');await page.locator('#print-size').selectOption('large');await page.locator('#preview-list').click();assert.ok(await page.locator('#preview-dialog').evaluate(n=>n.open));assert.equal(await page.locator('#preview-content tbody tr').count(),2);assert.equal(await page.evaluate(()=>closeTopSheet()),true);assert.equal(await page.evaluate(()=>closeTopSheet()),true);assert.equal(await page.evaluate(()=>closeTopSheet()),false);
await page.locator('#show-all').click();assert.equal(await page.locator('.shot').count(),73);
await setup();await page.locator('.settings>summary').click();await page.locator('#factor-mx125').fill('1.1');await page.locator('#calibration-form button[type="submit"]').click();assert.match(await page.locator('#toast').textContent(),/factors saved/);await close();
for(const width of [320,393,740]){await page.setViewportSize({width,height:852});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await setup();assert.ok(await page.locator('#sheet-dialog').evaluate(n=>n.scrollWidth<=n.clientWidth+1));await close();}
await page.setViewportSize({width:393,height:852});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({animations:'disabled',path:new URL('verification/modern-main.png',dir).pathname});
await setup();await page.screenshot({animations:'disabled',path:new URL('verification/modern-sheet.png',dir).pathname});await close();
await page.locator('#results').scrollIntoViewIfNeeded();await page.screenshot({animations:'disabled',path:new URL('verification/modern-results.png',dir).pathname});
await setup();await page.locator('#source-mode').selectOption('decay');await page.locator('#reference-ci').fill('100');
const date=await page.evaluate(()=>today());await page.locator('#reference-date').fill(date);await page.locator('button[form="activity-form"]').click();assert.match(await page.locator('#freshness').textContent(),/Calculated for today/);assert.match(await page.locator('#source-number').textContent(),/100/);
await page.reload();assert.match(await page.locator('#source-number').textContent(),/100/);
const printHtml=await page.evaluate(()=>makePrintDocument());assert.match(printHtml,/Source activity/);const printPage=await context.newPage();await printPage.setContent(printHtml);assert.equal(await printPage.locator('tbody tr').count(),73);
await setup();const original=Number(await page.locator('.shot').first().getAttribute('data-seconds'));
await page.locator('#target-density').selectOption('2');const low=Number(await page.locator('.shot').first().getAttribute('data-seconds'));assert.ok(low<original);assert.match(await page.locator('#film-overview').textContent(),/Density 2.0/);
if(!await page.locator('.settings').evaluate(n=>n.open))await page.locator('.settings>summary').click();
assert.equal(await page.locator('#factor-mx125').inputValue(),'1');await page.locator('#factor-mx125').fill('1.2');await page.locator('#calibration-form button[type="submit"]').click();
await page.locator('#target-density').selectOption('3');assert.equal(await page.locator('#factor-mx125').inputValue(),'1.1');assert.equal(Number(await page.locator('.shot').first().getAttribute('data-seconds')),original);
await page.locator('#target-density').selectOption('2');assert.equal(await page.locator('#factor-mx125').inputValue(),'1.2');await close();
await page.reload();assert.equal(await page.locator('#target-density').inputValue(),'2');assert.equal(await page.locator('#factor-mx125').inputValue(),'1.2');
await printPage.setContent(await page.evaluate(()=>makePrintDocument()));assert.match(await printPage.locator('body').textContent(),/Target density: 2.0/);
const displayed=await page.locator('.time').allTextContents(),printed=await printPage.locator('td.time').allTextContents();assert.deepEqual(printed,displayed);
console.log('PASS: density persistence, recalculation, independent factors and exact screen/print agreement.');
await setup();
if(!await page.locator('.settings').evaluate(n=>n.open))await page.locator('.settings>summary').click();
await page.locator('#cal-helper>summary').click();
await page.locator('#helper-size').selectOption('2');await page.locator('#helper-film').selectOption('ix50');await page.locator('#helper-density').selectOption('3');await page.locator('#helper-ci').fill('25');await page.locator('#helper-time').fill('10');
await page.locator('#helper-form button').click();assert.equal(await page.locator('#helper-review').isVisible(),true);
assert.match(await page.locator('#helper-review-text').textContent(),/8.445 s/);await page.locator('#helper-review').scrollIntoViewIfNeeded();await page.screenshot({animations:'disabled',path:new URL('verification/calibration-helper.png',dir).pathname});
assert.equal(await page.evaluate(()=>readSetting('factor.user-r-chart-v1.3.ix50',null)),1);
await page.locator('#helper-time').fill('11');assert.equal(await page.locator('#helper-review').isVisible(),false);
await page.locator('#helper-time').fill('10');await page.locator('#helper-form button').click();await page.locator('#helper-save').click();
assert.ok(Math.abs(Number(await page.evaluate(()=>readSetting('factor.user-r-chart-v1.3.ix50',null)))-10/8.444651998708329)<1e-12);
assert.equal(await page.locator('#factor-ix50').inputValue(),'1');
await page.locator('#helper-unit').selectOption('60');await page.locator('#helper-time').fill('100');await page.locator('#helper-form button').click();assert.match(await page.locator('#helper-error').textContent(),/outside/);
await page.locator('#helper-time').fill('0.2');await page.locator('#helper-form button').click();assert.match(await page.locator('#helper-review-text').textContent(),/Successful exposure: 12 s/);
await page.locator('#helper-size').selectOption('4');assert.equal(await page.locator('#helper-review').isVisible(),false);assert.deepEqual(await page.locator('#helper-film option').evaluateAll(ns=>ns.map(n=>n.value)),['d5','t200','ix80']);
await page.locator('#helper-ci').fill('0');await page.locator('#helper-form button').click();assert.match(await page.locator('#helper-error').textContent(),/activity/);
await page.locator('#target-density').selectOption('3');assert.ok(Math.abs(Number(await page.locator('#factor-ix50').inputValue())-10/8.444651998708329)<1e-12);await close();await page.reload();assert.ok(Math.abs(Number(await page.locator('#factor-ix50').inputValue())-10/8.444651998708329)<1e-12);
console.log('PASS: helper review-before-save, unrounded baseline, stale-review invalidation, units, bounds, film groups, density isolation and persistence.');
assert.deepEqual(errors,[]);await browser.close();console.log('PASS: modern sheets, Back/close, film buttons, segments, notifications, filter persistence, calibration and three widths.');
